### ISSUE TITLE
Event pooling no longer an issue

### ISSUE THREAD

**Issue by mrandolph83** [learn-co-curriculum/react-events-in-detail#10]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

> Add a link to the assignment in Canvas here.

## What should be changed?

I had not heard of the function event.persist, so I looked it up in the React docs. According to the docs, event pooling is no longer an issue as of v17. Maybe note that this problem has been addressed in v17, or take the lesson down

Docs link:
https://reactjs.org/docs/events.html

Copy/paste info from docs:
Note: As of v17, e.persist() doesn’t do anything because the SyntheticEvent is no longer pooled.

> Suggest your change here. Let us know what section or line of the Readme needs
> to be updated, and any proposed corrections. Include the line number(s) if
> possible.

## Additional context

> Add any other context about the problem here.

**Comment by ihollander** [comment]
Hi @mrandolph83 - thanks for raising this issue! Since many companies still use older versions of React (prior to v17), we feel it's still important that students are introduced to this topic so that they are able to understand how to deal with legacy code. It's also historically been a common question asked by React interviewers. However, we will make some updates to the readme that mention how it is no longer an issue as of React version 17!
